CREATE TABLE [dbo].[DemoWasteInOps]
(
    [Name]                   NVARCHAR (MAX) NULL,
    [Description]                  NVARCHAR (MAX) NULL,
    [Facility]       NVARCHAR (MAX) NULL,
    [Organizational Unit]          NVARCHAR (MAX) NULL,
    [Evidence]       NVARCHAR (MAX) NULL,
    [Quantity]       NVARCHAR (MAX) NULL,
    [Quantity Unit]       NVARCHAR (MAX) NULL,
    [Cost]       NVARCHAR (MAX) NULL,
    [Cost Unit]       NVARCHAR (MAX) NULL,
    [Waste Quantity]       NVARCHAR (MAX) NULL,
    [Waste Quantity Unit]       NVARCHAR (MAX) NULL,
    [Distance]       NVARCHAR (MAX) NULL,
    [Distance Unit]       NVARCHAR (MAX) NULL,
    [Fuel Type]       NVARCHAR (MAX) NULL,
    [Fuel Quantity]       NVARCHAR (MAX) NULL,
    [Fuel Quantity Unit]       NVARCHAR (MAX) NULL,
    [Data Quality Type]      NVARCHAR (MAX) NULL,
    [Spend Type]       NVARCHAR (MAX) NULL,
    [Transport Mode]       NVARCHAR (MAX) NULL,
    [Disposal Method]       NVARCHAR (MAX) NULL,
    [Material]       NVARCHAR (MAX) NULL,
    [Industrial Process Type]       NVARCHAR (MAX) NULL,
    [Meter Number]       NVARCHAR (MAX) NULL,
    [Value Chain Partner]       NVARCHAR (MAX) NULL,
    [Transaction Date]       NVARCHAR (MAX) NULL,
    [Consumption Start Date] NVARCHAR (MAX) NULL,
    [Consumption End Date]   NVARCHAR (MAX) NULL,
    [Origin Correlation ID]  NVARCHAR (MAX) NULL,
    [Car Model]              NVARCHAR (MAX) NULL,
    [Car Interior]           NVARCHAR (MAX) NULL,
    [Sound System]           NVARCHAR (MAX) NULL,
    [Assembly Count]         NVARCHAR (MAX) NULL
);